apiVersion: apps/v1
kind: Deployment
metadata:
  name: seatsnap-app
  labels:
    app: seatsnap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seatsnap
  template:
    metadata:
      labels:
        app: seatsnap
    spec:
      containers:
      - name: seatsnap-container
        image: aj2005/seatsnap:latest  # Changed to your Docker image
        ports:
        - containerPort: 80  # Changed to 80 because Nginx serves on port 80