apiVersion: v1
kind: Service
metadata:
  name: bms-service
  labels:
    app: bms
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80  # Changed to 80 because Nginx serves on port 80
  selector:
    app: bms